Create db from sql file
suprugafad/shop_solvd pull request #6
Opened 2023-03-28 09:34 UTC by suprugafad

Create db from sql file and connect it
sql file - shop.sql
db is creating in file shopdb.js
add new controller for products to test this db, but also its working with controller for users

2023-03-29 08:12 UTC, hover024 requested changes

2023-03-29 08:12 UTC, hover024 commented on controllers/authController.js
> +    const user = await pool.query('SELECT * FROM users WHERE email = $1', [email]);
извлекать все поля, плохая практика, специфицируй пожалуйста, создай DTO и бери название полей оттуда

2023-03-29 08:12 UTC, hover024 commented on controllers/productController.js
> +    await pool.query('SELECT * FROM product ORDER BY id ASC', (error, results) => {
названия полей через DTO

2023-03-29 08:12 UTC, hover024 commented on controllers/userController.js
> +    await pool.query('SELECT * FROM users ORDER BY id ASC', (error, results) => {
DTO

2023-03-29 08:12 UTC, hover024 commented on controllers/userController.js
> +    await pool.query(`SELECT * FROM users WHERE id = ${id}`, (error, results) => {
DTO

2023-03-29 08:12 UTC, hover024 commented on controllers/userController.js
> +      if (error) {
что я говорил про идемпотентность?

2023-03-29 08:12 UTC, hover024 commented on db/index.js
> +  password: 'poshik',
в энв все

2023-03-29 08:12 UTC, hover024 commented on db/shop.sql
> +-- COMMIT;
выглядит неплохо, а покажи что в итоге нарисовалось

2023-03-29 08:12 UTC, hover024 commented on db/shopdb.js
> +  user: 'postgres',
в энв все

2023-03-31 12:32 UTC, suprugafad commented on controllers/authController.js
> +    const user = await pool.query('SELECT * FROM users WHERE email = $1', [email]);
сделала

2023-03-31 12:33 UTC, suprugafad commented on controllers/productController.js
> +    await pool.query('SELECT * FROM product ORDER BY id ASC', (error, results) => {
сделала

2023-03-31 12:33 UTC, suprugafad commented on controllers/userController.js
> +    await pool.query('SELECT * FROM users ORDER BY id ASC', (error, results) => {
сделала

2023-03-31 12:33 UTC, suprugafad commented on controllers/userController.js
> +    await pool.query(`SELECT * FROM users WHERE id = ${id}`, (error, results) => {
сделала

2023-03-31 12:33 UTC, suprugafad commented on controllers/userController.js
> +      if (error) {
исправила

2023-03-31 12:56 UTC, suprugafad commented on db/index.js
> +  password: 'poshik',
сделала

2023-03-31 13:02 UTC, suprugafad commented on db/shopdb.js
> +  user: 'postgres',
сделала

2023-04-06 11:33 UTC, hover024 approved these changes

2023-04-06 12:26 UTC, merged